version: '3.9'

services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: root3
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"  # เปลี่ยนพอร์ตของ adminer เป็น 8081 บนโฮสต์

  web:
    image: nginx
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - "8080:80"  # web จะยังคงใช้พอร์ต 8080 บนโฮสต์
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80

  mongo1:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root1
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"

  mongo2:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root2
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27018:27017"
